
replicaCount: 1

image:
  repository: andreyab404/mainapp
  pullPolicy: IfNotPresent
  tag: "1.9"

service:
  # type: ClusterIP
  type: NodePort
  port: 3003


ingress:
  enabled: false

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30


readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 7
  failureThreshold: 3

livenessProbe:
  initialDelaySecons: 20
  periodSeconds: 15
  timeoutSeconds: 7
  failureThreshold: 3

env:
  PORT: 3003
  DATABASE_URL: postgresql://user1:pass1@postgresl-postgresql:5432/dz_base1
  REDIS_URL: redis://redis-master:6379/1
  PRICE_URL: http://priceapp:3001/price/
  COORD_URL: http://priceapp:3001/coord/
  COUNT_ORD: 3
  RABBITMQ_URL: amqp://user1:password1@rabbitmq:5672/
  RABBITMQ_RE_COUNT: 100
  CELERY_BROKER_URL: redis://redis-master:6379/0
  AWS_REGION: eu-west-1
  LOCALSTACK_URL: http://localstack:4566
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy
  SQS_QUEUE_NAME: pay_queue
  SNS_TOPIC_NAME: PayTopic
  LOGGING_LEVEL: DEBUG
  SNS_ENDPOINT: http://mainapp:3003/pay/status