replicaCount: "1"

app:
  name: "paysrv"

image:
  repository: "andreyab404/paysrv"
  tag: "1.8"

env:
  AWS_ACCESS_KEY_ID: dummy
  AWS_REGION: eu-west-1
  AWS_SECRET_ACCESS_KEY: dummy
  LOCALSTACK_URL: http://localstack:4566
  PYTHONUNBUFFERED: "1"
  SQS_QUEUE_NAME: pay_queue
  SNS_TOPIC_NAME: PayTopic
  LOGGING_LEVEL: DEBUG

resources:
  requests:
    memory: "32Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
