replicaCount: 1

image:
  repository: andreyab404/mainapp
  tag: "1.9"
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 32Mi
    cpu: 100m

env:
  DATABASE_URL: postgresql://user1:pass1@postgresl-postgresql:5432/dz_base1
  REDIS_URL: redis://redis-master:6379/1
  CELERY_BROKER_URL: redis://redis-master:6379/0
  AWS_REGION: eu-west-1
  LOCALSTACK_URL: http://localstack:4566
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy
  S3_BUCKET_NAME: bucket
  

command:
  - celery
  - -A
  - app.celery_config
  - worker
  - --pool=gevent
  - --loglevel=info
  - -Q
  - cron_tasks
